In [39]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler,LabelEncoder
#from sklearn.metrics import r2_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

In [22]:
df=pd.read_csv("wineQualityReds.csv")
df.head()
import warnings
warnings.filterwarnings("ignore")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 13 columns):
Unnamed: 0              1599 non-null int64
fixed.acidity           1599 non-null float64
volatile.acidity        1599 non-null float64
citric.acid             1599 non-null float64
residual.sugar          1599 non-null float64
chlorides               1599 non-null float64
free.sulfur.dioxide     1599 non-null float64
total.sulfur.dioxide    1599 non-null float64
density                 1599 non-null float64
pH                      1599 non-null float64
sulphates               1599 non-null float64
alcohol                 1599 non-null float64
quality                 1599 non-null int64
dtypes: float64(11), int64(2)
memory usage: 162.5 KB


In [24]:
df.quality[(df.quality)==8]='bad'
df.quality[(df.quality)==7]='bad'
df.quality[(df.quality)==5]='Average'
df.quality[(df.quality)==6]='Average'
df.quality[(df.quality)==4]='Good'
df.quality[(df.quality)==3]='Good'

In [25]:
df['quality'].value_counts()

Average    1319
bad         217
Good         63
Name: quality, dtype: int64

In [26]:
lab = LabelEncoder()
df['quality'] = lab.fit_transform(df["quality"])

In [27]:
df.head()

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
0           1            7.4              0.70         0.00             1.9   
1           2            7.8              0.88         0.00             2.6   
2           3            7.8              0.76         0.04             2.3   
3           4           11.2              0.28         0.56             1.9   
4           5            7.4              0.70         0.00             1.9   

   chlorides  free.sulfur.dioxide  total.sulfur.dioxide  density    pH  \
0      0.076                 11.0                  34.0   0.9978  3.51   
1      0.098                 25.0                  67.0   0.9968  3.20   
2      0.092                 15.0                  54.0   0.9970  3.26   
3      0.075                 17.0                  60.0   0.9980  3.16   
4      0.076                 11.0                  34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        0  
1       0.68      9.8        0  
2       0.65      9.8        0  
3       0.58      9.8        0  
4       0.56      9.4        0

In [28]:
df['quality'].value_counts()

0    1319
2     217
1      63
Name: quality, dtype: int64

In [29]:
X = df.iloc[ :,1:11]
X.head()

fixed.acidity  volatile.acidity  citric.acid  residual.sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free.sulfur.dioxide  total.sulfur.dioxide  density    pH  sulphates  
0                 11.0                  34.0   0.9978  3.51       0.56  
1                 25.0                  67.0   0.9968  3.20       0.68  
2                 15.0                  54.0   0.9970  3.26       0.65  
3                 17.0                  60.0   0.9980  3.16       0.58  
4                 11.0                  34.0   0.9978  3.51       0.56

In [30]:
Y = df.iloc[:,-1]
Y.head()
Y.value_counts()

0    1319
2     217
1      63
Name: quality, dtype: int64

In [31]:
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [32]:
sc = StandardScaler()

In [33]:
X_Train = sc.fit_transform(X_Train)
X_Test = sc.transform(X_Test)

In [34]:
z = KNeighborsClassifier(n_neighbors=15,metric='minkowski',p=5)
z.fit(X_Train,Y_Train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=15, p=5,
           weights='uniform')

In [35]:
Y_predict=z.predict(X_Test)

In [38]:
accuracy_score(Y_Test,Y_predict)

0.853125

In [19]:
print(confusion_matrix(Y_Test, Y_predict))  
print(classification_report(Y_Test, Y_predict)) 

[[265   0  12]
 [ 13   0   0]
 [ 22   0   8]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92       277
           1       0.00      0.00      0.00        13
           2       0.40      0.27      0.32        30

   micro avg       0.85      0.85      0.85       320
   macro avg       0.43      0.41      0.41       320
weighted avg       0.80      0.85      0.83       320



In [40]:
pwd

'C:\\Users\\jaya'